version: '3.4'

services:
    siremudb:
        build:
            context: .
            dockerfile: ./database/Dockerfile
        ports:
            - "1443:1433"
        volumes:
            - sqlvolume:/var/opt/mssql

    siremuservercanciones:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "25112:25112"
        volumes:
            - /usr/src/

    siremuserverlistas:
        build:
            context: .
            dockerfile: ./backend2/Dockerfile
        ports:
            - "25111:25111"
        volumes:
            - /usr/src/

    siremuservercuentas:
        build:
            context: .
            dockerfile: ./backend3/Dockerfile
        ports:
            - "25113:25113"
        volumes:
            - /usr/src/
            
volumes:
    sqlvolume:
