# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: manejoListas.proto for package 'mnjListas'

require 'grpc'
require 'manejoListas_pb'

module MnjListas
  module ManejoListas
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mnjListas.ManejoListas'

      rpc :AgregarQuitarCancionesLista, ListaAA, RespuestaRegistro
      rpc :AgregarListaAMeGusta, ListaAG, RespuestaRegistro
      rpc :BuscarListas, NombreLista, ListaListas
      # rpc ConsultarAparicion(idCancion) returns (ListaListas){}
      rpc :ConsultarLista, ListaReproduccion, ListaCanciones
      # rpc ConsultarListasPopulares(IdUsuario) returns (ListaCanciones){}
      # rpc ConsultarMisCanciones(IdUsuario) returns(ListaCanciones){}
      rpc :ConsultarMisListas, IdUsuario, ListaListas
      rpc :ConsultarMisListasAgregadas, IdUsuario, ListaListas
      rpc :ConsultarMisListasDefault, IdUsuario, ListaListas
      rpc :CrearListaReproduccion, ListaAG, RespuestaRegistro
    end

    Stub = Service.rpc_stub_class
  end
end
