# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manejoListas.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("manejoListas.proto", :syntax => :proto3) do
    add_message "mnjListas.ListaAG" do
      optional :idUsuario, :int32, 1
      optional :listaAAgregar, :message, 2, "mnjListas.ListaReproduccion"
    end
    add_message "mnjListas.RespuestaRegistro" do
      optional :respuesta, :bool, 1
      optional :codigoError, :string, 2
    end
    add_message "mnjListas.ListaAA" do
      optional :idUsuario, :int32, 1
      optional :idLista, :int32, 2
      repeated :idCanciones, :int32, 3
      optional :agregar, :bool, 4
    end
    add_message "mnjListas.NombreLista" do
      optional :nombre, :string, 1
    end
    add_message "mnjListas.ListaListas" do
      repeated :listas, :message, 1, "mnjListas.ListaReproduccion"
    end
    add_message "mnjListas.ListaCanciones" do
      repeated :canciones, :message, 1, "mnjListas.Cancion"
    end
    add_message "mnjListas.IdUsuario" do
      optional :id, :int32, 1
    end
    add_message "mnjListas.CancionPP" do
      optional :contenido, :bytes, 1
    end
    add_message "mnjListas.Album" do
      optional :id, :int32, 1
      optional :compania, :string, 2
      optional :fechaLanzamiento, :string, 3
      optional :ilustracion, :bytes, 4
      optional :nombre, :string, 5
    end
    add_message "mnjListas.Cancion" do
      optional :id, :int32, 1
      optional :artista, :string, 2
      optional :duracion, :string, 3
      optional :esPRomocion, :bool, 4
      optional :esPublica, :bool, 5
      optional :genero, :string, 6
      optional :likes, :int32, 7
      optional :nombre, :string, 8
      optional :idAlbum, :int32, 9
      optional :nombreAlbum, :string, 10
    end
    add_message "mnjListas.ListaReproduccion" do
      optional :id, :int32, 1
      optional :descripcion, :string, 2
      optional :esDefault, :bool, 3
      optional :esPublica, :bool, 4
      optional :ilustracion, :bytes, 5
      optional :likes, :int32, 6
      optional :nombre, :string, 7
      optional :idCreador, :int32, 8
      optional :nombreCreador, :string, 9
    end
  end
end

module MnjListas
  ListaAG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaAG").msgclass
  RespuestaRegistro = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.RespuestaRegistro").msgclass
  ListaAA = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaAA").msgclass
  NombreLista = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.NombreLista").msgclass
  ListaListas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaListas").msgclass
  ListaCanciones = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaCanciones").msgclass
  IdUsuario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.IdUsuario").msgclass
  CancionPP = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.CancionPP").msgclass
  Album = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.Album").msgclass
  Cancion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.Cancion").msgclass
  ListaReproduccion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaReproduccion").msgclass
end
