# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: loginMS.proto for package 'loginMS'

require 'grpc'
require 'loginMS_pb'

module LoginMS
  module Login
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'loginMS.Login'

      rpc :IniciarSesion, Cuenta, RespuestaLogin
      rpc :BuscarCancion, Cancion, stream(Pedazo)
    end

    Stub = Service.rpc_stub_class
  end
end
