# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginMS.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("loginMS.proto", :syntax => :proto3) do
    add_message "loginMS.Cuenta" do
      optional :usuario, :string, 1
      optional :contra, :string, 2
    end
    add_message "loginMS.RespuestaLogin" do
      optional :respuesta, :bool, 1
    end
    add_message "loginMS.Cancion" do
      optional :id, :int32, 1
    end
    add_message "loginMS.Pedazo" do
      optional :contenido, :bytes, 1
    end
  end
end

module LoginMS
  Cuenta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loginMS.Cuenta").msgclass
  RespuestaLogin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loginMS.RespuestaLogin").msgclass
  Cancion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loginMS.Cancion").msgclass
  Pedazo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loginMS.Pedazo").msgclass
end
