# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manejoCanciones.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("manejoCanciones.proto", :syntax => :proto3) do
    add_message "NombreCancion" do
      optional :nombre, :string, 1
    end
    add_message "AlbumAG" do
      optional :idUsuario, :int32, 1
      optional :album, :message, 2, "Album"
    end
    add_message "CancionAG" do
      optional :idUsuario, :int32, 1
      optional :cancion, :message, 2, "Cancion"
      optional :idAlbum, :int32, 3
    end
    add_message "IdUsuario" do
      optional :id, :int32, 1
    end
    add_message "IdLista" do
      optional :id, :int32, 1
    end
    add_message "ListaCanciones" do
      repeated :canciones, :message, 1, "Cancion"
    end
    add_message "ListaAlbums" do
      repeated :albums, :message, 1, "Album"
    end
    add_message "RespuestaCanciones" do
      optional :respuesta, :bool, 1
      optional :codigoError, :string, 2
    end
    add_message "CancionPP" do
      optional :idCancion, :int32, 1
      optional :contenido, :bytes, 2
    end
    add_message "Album" do
      optional :id, :int32, 1
      optional :compania, :string, 2
      optional :fechaLanzamiento, :string, 3
      optional :ilustracion, :bytes, 4
      optional :extensionIlustracion, :string, 5
      optional :nombre, :string, 6
    end
    add_message "Cancion" do
      optional :id, :int32, 1
      optional :artista, :string, 2
      optional :duracion, :string, 3
      optional :esPRomocion, :bool, 4
      optional :esPublica, :bool, 5
      optional :genero, :string, 6
      optional :likes, :int32, 7
      optional :nombre, :string, 8
      optional :album, :message, 9, "Album"
    end
  end
end

NombreCancion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NombreCancion").msgclass
AlbumAG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AlbumAG").msgclass
CancionAG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancionAG").msgclass
IdUsuario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IdUsuario").msgclass
IdLista = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IdLista").msgclass
ListaCanciones = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ListaCanciones").msgclass
ListaAlbums = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ListaAlbums").msgclass
RespuestaCanciones = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RespuestaCanciones").msgclass
CancionPP = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancionPP").msgclass
Album = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Album").msgclass
Cancion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Cancion").msgclass
