# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manejoListas.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("manejoListas.proto", :syntax => :proto3) do
    add_message "mnjListas.ListaAG" do
      optional :idUsuario, :int32, 1
      optional :listaAAgregar, :message, 2, "mnjListas.ListaReproduccion"
    end
    add_message "mnjListas.RespuestaListas" do
      optional :respuesta, :bool, 1
      optional :codigoError, :string, 2
    end
    add_message "mnjListas.ListaAA" do
      optional :idUsuario, :int32, 1
      optional :idLista, :int32, 2
      repeated :idCanciones, :int32, 3
      optional :agregar, :bool, 4
    end
    add_message "mnjListas.NombreLista" do
      optional :nombre, :string, 1
    end
    add_message "mnjListas.ListaListas" do
      repeated :listas, :message, 1, "mnjListas.ListaReproduccion"
    end
    add_message "mnjListas.IdUsuario" do
      optional :id, :int32, 1
    end
    add_message "mnjListas.ListaReproduccion" do
      optional :id, :int32, 1
      optional :descripcion, :string, 2
      optional :esDefault, :bool, 3
      optional :esPublica, :bool, 4
      optional :ilustracion, :bytes, 5
      optional :extensionIlustracion, :string, 6
      optional :likes, :int32, 7
      optional :nombre, :string, 8
      optional :idCreador, :int32, 9
      optional :nombreCreador, :string, 10
    end
  end
end

module MnjListas
  ListaAG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaAG").msgclass
  RespuestaListas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.RespuestaListas").msgclass
  ListaAA = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaAA").msgclass
  NombreLista = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.NombreLista").msgclass
  ListaListas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaListas").msgclass
  IdUsuario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.IdUsuario").msgclass
  ListaReproduccion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjListas.ListaReproduccion").msgclass
end
