# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: manejoCanciones.proto for package ''

require 'grpc'
require 'manejoCanciones_pb'

module ManejoCanciones
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'manejoCanciones'

    rpc :BuscarCanciones, NombreCancion, ListaCanciones
    rpc :CrearAlbum, AlbumAG, RespuestaCanciones
    rpc :ConsultarMisCanciones, IdUsuario, ListaCanciones
    rpc :ConsultarCancionesEnPromocion, IdUsuario, ListaCanciones
    rpc :ConsultarAlbums, IdUsuario, ListaAlbums
    rpc :ConsultarCancionesAlbum, Album, ListaCanciones
    rpc :ConsultarCancionesLista, IdLista, ListaCanciones
    rpc :GenerarRadio, Cancion, ListaCanciones
    rpc :ModificarAlbum, AlbumAG, RespuestaCanciones
    rpc :ReproducirCancion, Cancion, stream(CancionPP)
    rpc :RegistrarCancion, CancionAG, RespuestaCanciones
    rpc :SubirCancion, stream(CancionPP), RespuestaCanciones
  end

  Stub = Service.rpc_stub_class
end
