# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: manejoCuentas.proto for package 'mnjCuentas'

require 'grpc'
require 'manejoCuentas_pb'

module MnjCuentas
  module ManejoCuentas
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mnjCuentas.ManejoCuentas'

      rpc :IniciarSesion, Usuario, RespuestaCuentas
      rpc :RegistrarUsuario, Usuario, RespuestaCuentas
      rpc :ModificarUsuario, Usuario, RespuestaCuentas
    end

    Stub = Service.rpc_stub_class
  end
end
