# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manejoCuentas.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("manejoCuentas.proto", :syntax => :proto3) do
    add_message "mnjCuentas.RespuestaCuentas" do
      optional :respuesta, :bool, 1
      optional :codigoError, :string, 2
    end
    add_message "mnjCuentas.Usuario" do
      optional :nombre, :string, 1
      optional :contrasenia, :string, 2
      optional :correo, :string, 3
      optional :esCreadorContenido, :bool, 4
      optional :fechaNacimiento, :string, 5
      optional :genero, :string, 6
      optional :usuario, :string, 7
      optional :apellido, :string, 8
      optional :id, :int32, 9
    end
  end
end

module MnjCuentas
  RespuestaCuentas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjCuentas.RespuestaCuentas").msgclass
  Usuario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mnjCuentas.Usuario").msgclass
end
